sudo: required
services:
  - docker

before_install:
  - docker build -t vsevak/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run vsevak/react-test npm test -- --coverage

after_sucess:
  - docker build -t vsevak/multi-client ./client
  - docker build -t vsevak/multi-nginx ./nginx
  - docker build -t vsevak/multi-server ./server
  - docker build -t vsevak/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push vsevak/multi-client
  - docker push vsevak/multi-nginx
  - docker push vsevak/multi-server
  - docker push vsevak/multi-worker
